name: Deploy and Execute Script on EC2

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Debugging
      run: |
        echo "Checking for Host: ${{ secrets.HOSTNAME }}"
        echo "Checking for Username: ${{ secrets.USERNAME }}"
        if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "SSH_PRIVATE_KEY is empty"
        else
          echo "SSH_PRIVATE_KEY is set"
        fi

    - name: List files in working directory
      run: |
        echo "Listing files in working directory:"
        ls -alh

    - name: Check if script.py and requirements.txt exist
      run: |
        if [ ! -f script.py ]; then
          echo "script.py does not exist"
          exit 1
        fi
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt does not exist"
          exit 1
        fi

    - name: Copy script.py and requirements.txt to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "script.py,requirements.txt"
        target: "/home/ubuntu/Diabetes"

    - name: Execute script.py on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/Diabetes
          mkdir -p tasks
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
          python3 script.py
